---
- id: 1487766199555
  name: Play
  type: play
  root: true
  next: 1487766226006
  resource:
    guid: ee2538ba-9291-29a3-40c8-924ce96a5d86
- id: 1487766226006
  name: 1ToRecord2ToListen
  type: menu
  root: false
  next:
  store: menuchoice
  options:
  - next: 1487766331807
    is_default: false
    number: '1'
  - next: 1487766339758
    is_default: false
    number: '2'
  invalid_resource:
    guid: 0e3593d7-c30c-39f1-10ca-ab227e47cd15
  explanation_resource:
    guid: 397b08e6-45a2-1fb5-967e-0d3ce1b4c777
  options_resource:
    guid: f201141b-1ef4-a482-dda1-9905fd90cde0
  timeout: 5
  number_of_attempts: '3'
  default: 1487766322300
- id: 1487766322300
  name: Hang Up
  type: hang_up
  root: false
  next:
- id: 1487766331807
  name: Record
  type: record
  root: false
  next: 1487766986007
  timeout: '180'
  stop_key: '1'
  explanation_resource:
    guid: 489a1ea5-93d4-3657-3130-147b5ccb73bb
  confirmation_resource:
    guid: 442b4217-b83f-0e47-966a-5853eb0d3c90
- id: 1487766339758
  name: Play
  type: play
  root: false
  next: 1487767026437
  resource:
    guid: 35948996-7295-b5f6-adde-45961e8bcd58
- id: 1487766986007
  name: Hang Up
  type: hang_up
  root: false
  next:
- id: 1487767026437
  name: External Action
  type: playloop
  loop_dir: '/opt/voiceofhimalaya/playloop'
  root: false
  next:
  bindings: []
